### ISSUE TITLE
Configure how the locale name will be displayed

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/LocaleComboBox#2]
### Feature proposal

Depending on the purpose of the field, it might make sense to display the locale names in the UI locale. Google Translate follows that approach:
![image](https://github.com/user-attachments/assets/3b73de3e-d71a-451b-9a8f-08db632c7096)

In other scenarios, it makes sense to display the locale name in the locale itself (so that users can select their locale, which will be written in their own language). Facebook follows that approach:
![image](https://github.com/user-attachments/assets/2c95688a-251d-4315-89e0-c977fe2aacfb)

**Comment by elPeiretti** [comment]
In my opinion, Facebook's approach is more user-friendly than Google's. If a user accidentally selects an unfamiliar locale or language, it can be challenging to find the intended locale afterwards.

**Comment by mlopezFC** [comment]
Let's go ahead with the Facebook approach, and also let's aim to improve the demo, it seems to be pretty empty right now. Some other ideas:

- It should be possible to configure if I want to display, the locale in english, the locale in the locale it self, or both
- It should be possible if I want to select the locale, or convert it to select only the country (like a country selector)
- It would be great to be able to only allow the selection for certain locales / countries

Based on that we could make the demo more interesting, right now it seems pretty empty. (BTW make the combo box wider in the demo)
