### ISSUE TITLE
Allow the selection for certain locales 

### ISSUE THREAD

**Issue by elPeiretti** [FlowingCode/LocaleComboBox#4]
### Feature proposal

Based on @mlopezFC 's comment on #3 _"It would be great to be able to only allow the selection for certain locales / countries"_.

What ideas come to your minds about it?

Currently, the addon is limited by the flag-icons package (which provides the flag icons). It renders the flags based on ISO 3166-1-alpha-2 (a 2 letter country code). Because of this, all the supported locales by the addons are:
```java
  public static List<Locale> getAvailableSupportedLocales() {
    return Arrays.stream(Locale.getAvailableLocales()).filter(loc -> loc.getCountry().length() == 2)
        .toList();
  }
```

Maybe it would be a good option to have a helper class or static methods to build only supported locales. Or, we could simply allow the developer to set the locales that they want like:
```java
List<Locale> myDesiredLocales; // list with some locales

LocaleComboBox myCombo = new LocaleComboBox(myDesiredLocales);
// or
myCombo.setItems(myDesiredLocales);
```
The issue with this approach is that it would be possible to add unsupported locales (for which the flags won't show)

So, i'm pretty unsure about it 🤔. Let me know what you think.

**Comment by javier-godoy** [comment]
Given that the no-args constructor already does `setItems(...)`, it makes sense to have a `(List<Locale>)` constructor.

`setItems(List<Locale>)` also seems useful, because there is no reason to prevent changing the items on an existing instance.

**Comment by mlopezFC** [comment]
Regarding specifying locales without flags, I would render a generic icon instead of that flag. Maybe even we could provide an option for disabling showing the flags. The component is still useful without flags.
